travis:
  secure:
    BINSTAR_TOKEN: ahB+uetkZXa2JwYWrLhsSCbGt3ggzn2oP95QXCP8t8m/4UzmjDNI7Ykt2Mhwlx98W4nxRj2lQpEiErr4mLQlnvVOasb5Kajyx1fQMHw8SL3xX1xULb/6WOcCShyaiPCN985jOkWMDc8io4whRaKIuS7nTPU9H3qfVUrW9FnRIPb49vvbsskKMvo4fBvCdesSOFFpAV+gtt7azrUhGR/IFNMX+Vx0luJsM4rFcLuda7/IfI3gER6ON+R0SDTaX9/S9IgSawtIlpC0fG+2+INlB8uinMGQnOAUJDDuedDcIjVrUmnDa+nXrlS7kfXc+j9B3btEqhnAo7Un3TLuvIdsZVMbAUiOuUJv09jTkm2yUYEBquYLTHGvTKAgksL08F2E1Pp+IoO5a19Lp7GKntCN3Pw3Q3RR9RkRBNwvOFQV+D7FKOpokvWYBzPVPWTXdGR6HewSyrkWR1ZaM8xJCY+Cit4xJY058KAmImgMRaab+SZaAF+P0AXj+qd0fygtEEMy/t/dNN/q6JbVxBH2f3DMq1uR99nAdh4cdEEZSmjLtTQVpFSjLOj7+gslrR3Gr+vpP5R3DNQD12+8b62m8A/jx0+cmwfFfeuz5tb+rGc/xefo1Y+uvciRre4yD7hebivR3eGNe9D1dweQcqgBlG4609tq57iXT5GvIXLn6nN2oKg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
